### ISSUE TITLE
which it is the steganography algorithm used in the application

### ISSUE THREAD

**Issue by hmvy88** [yashpunjabi/Steganography#2]
which it is the steganography algorithm used in the application

**Comment by Shazambom** [comment]
There were two methods used. If the first method  failed the second method would activate. First method: traditional least significant bit for every RGB value. Second method: find the closing block flag for the image in the file and append the other file data to the end of it. The first one will potentially fail because you only have (numPixels*3/8) bytes of data available and some hidden files may be too big. 

Both of these methods will increase the file size. The first one only slightly due to compression. The second obviously because you are dumping an entire extra file on the end. 

I hope this answers your question. (there are still some bugs here and there but the first method is the most stable method of steganography in this app)

**Comment by hmvy88** [comment]
Thank you very much for the reply

**Comment by hmvy88** [comment]
Please why you in EncoderTask use 

int numBitsPossible = ((buffer.getHeight() \* buffer.getWidth()) \* 3);
if (numBitsPossible < ((params[1].length() \* 8) + OVERHEAD_SIZE)) {
    return endEncode(params);
}

Maybe could be

int numBitsPossible = ((buffer.getHeight() \* buffer.getWidth()) \* 3)/8;
if (numBitsPossible < ((params[1].length()) + OVERHEAD_SIZE)) {
    return endEncode(params);
}

Or why you multiply
(params[1].length() \* 8) + OVERHEAD_SIZE)

Please help me

**Comment by Shazambom** [comment]
There is not a particular reason; however, Integer division is much less precise than integer multiplication. There could be some files that will just barely work with the first encoding type but will be deemed unable to do so by the method you are suggesting. (This is a very small edge case tho so its not that big of a deal).
